// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUY_ePOP7UdNiexR8ZZ_4NBO6Q_BuavlQ',
    appId: '1:451407143877:web:c550e62e441c2c930161ac',
    messagingSenderId: '451407143877',
    projectId: 'money-wise-v3',
    authDomain: 'money-wise-v3.firebaseapp.com',
    storageBucket: 'money-wise-v3.firebasestorage.app',
    measurementId: 'G-PCSP9SN825',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fCpiwgWpZInti2TvtjQIawD4wo_0Cbg',
    appId: '1:451407143877:android:3380b37874b7a20f0161ac',
    messagingSenderId: '451407143877',
    projectId: 'money-wise-v3',
    storageBucket: 'money-wise-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2h7kEDPhE_teVwxYrxDOiw_B6c3Dv2g',
    appId: '1:451407143877:ios:63dff552aafebbe00161ac',
    messagingSenderId: '451407143877',
    projectId: 'money-wise-v3',
    storageBucket: 'money-wise-v3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2h7kEDPhE_teVwxYrxDOiw_B6c3Dv2g',
    appId: '1:451407143877:ios:63dff552aafebbe00161ac',
    messagingSenderId: '451407143877',
    projectId: 'money-wise-v3',
    storageBucket: 'money-wise-v3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUY_ePOP7UdNiexR8ZZ_4NBO6Q_BuavlQ',
    appId: '1:451407143877:web:ff52aca02880dee40161ac',
    messagingSenderId: '451407143877',
    projectId: 'money-wise-v3',
    authDomain: 'money-wise-v3.firebaseapp.com',
    storageBucket: 'money-wise-v3.firebasestorage.app',
    measurementId: 'G-966HC2HJCW',
  );
}
